### ISSUE TITLE
Not such a great idea after all?

### ISSUE THREAD

**Issue by agentreno** [pbeshai/d3-webpack-loader#3]
Hello! Can you comment on why you decided you don't like this approach anymore (as mentioned in your README)? I need to do the same thing.

**Comment by pbeshai** [comment]
Someone more privy to the inner-workings of webpack suggested that doing things in this way would cause weird confusing problems with caching and how webpack determines files have changed at some point.

**Comment by agentreno** [comment]
Ahh.. sounds like it could lead to weird and wonderful behaviour later on. Thanks for the heads up.
